In [1]:
import numpy as np

In [2]:
list_1 = [10,20,30]
type(list_1)

list

In [3]:
np_array=np.array(list_1)
type(np_array)

numpy.ndarray

In [4]:
type(np_array.dtype)

numpy.dtype[int64]

In [5]:
np_array.shape

(3,)

In [7]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Series

In [8]:
import pandas as pd

In [9]:
my_list=[10,20,30]

In [11]:
srs=pd.Series(my_list)

In [12]:
srs

0    10
1    20
2    30
dtype: int64

In [13]:
type(srs)

pandas.core.series.Series

In [14]:
srs.index

RangeIndex(start=0, stop=3, step=1)

In [15]:
srs.values

array([10, 20, 30])

In [16]:
srs_array=srs.values

In [17]:
srs_array

array([10, 20, 30])

In [18]:
srs


0    10
1    20
2    30
dtype: int64

In [21]:
srs_new=pd.Series(srs,index=['a','b','c'])

In [23]:
srs_new

a   NaN
b   NaN
c   NaN
dtype: float64

In [ ]:
list_new=[33,22,11]
series_new=pd.Series(list)