In [1]:
import numpy as np

In [2]:
list_1 = [10,20,30]
type(list_1)

list

In [3]:
np_array=np.array(list_1)
type(np_array)

numpy.ndarray

In [4]:
type(np_array.dtype)

numpy.dtype[int64]

In [5]:
np_array.shape

(3,)

In [7]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Series

In [8]:
import pandas as pd

In [9]:
my_list=[10,20,30]

In [11]:
srs=pd.Series(my_list)

In [12]:
srs

0    10
1    20
2    30
dtype: int64

In [13]:
type(srs)

pandas.core.series.Series

In [14]:
srs.index

RangeIndex(start=0, stop=3, step=1)

In [15]:
srs.values

array([10, 20, 30])

In [16]:
srs_array=srs.values

In [17]:
srs_array

array([10, 20, 30])

In [18]:
srs


0    10
1    20
2    30
dtype: int64

In [21]:
srs_new=pd.Series(srs,index=['a','b','c'])

In [23]:
srs_new

a   NaN
b   NaN
c   NaN
dtype: float64

In [24]:
list_new=[33,22,11]
index=['a','b','c']
series_new=pd.Series(list_new,index=index)

In [25]:
series_new

a    33
b    22
c    11
dtype: int64

In [26]:
series_new.index

Index(['a', 'b', 'c'], dtype='object')

# DataFrames in Pandas

In [31]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],
               index=['a','b','c'],columns=['x','y','z'])

In [32]:
df

x  y  z
a  1  2  3
b  4  5  6
c  7  8  9

In [33]:
print('Shape :',df.shape)

Shape : (3, 3)


In [34]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [35]:
df.columns

Index(['x', 'y', 'z'], dtype='object')

# The Weather Dataset: Reading DataFrames from Files

In [36]:
weather_df=pd.read_csv('data/weather_2012.csv')


In [37]:
weather_df.shape

(8784, 8)

In [38]:
weather_df.index

RangeIndex(start=0, stop=8784, step=1)

In [39]:
weather_df.head()

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0  2012-01-01 00:00:00      -1.8                -3.9           86   
1  2012-01-01 01:00:00      -1.8                -3.7           87   
2  2012-01-01 02:00:00      -1.8                -3.4           89   
3  2012-01-01 03:00:00      -1.5                -3.2           88   
4  2012-01-01 04:00:00      -1.5                -3.3           88   

   Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                4              8.0           101.24                   Fog  
1                4              8.0           101.24                   Fog  
2                7              4.0           101.26  Freezing Drizzle,Fog  
3                6              4.0           101.27  Freezing Drizzle,Fog  
4                7              4.8           101.23                   Fog

In [40]:
weather_df['Date/Time'].head()

0    2012-01-01 00:00:00
1    2012-01-01 01:00:00
2    2012-01-01 02:00:00
3    2012-01-01 03:00:00
4    2012-01-01 04:00:00
Name: Date/Time, dtype: object

In [41]:
type(weather_df['Date/Time'].head())

pandas.core.series.Series

In [42]:
type(weather_df)

pandas.core.frame.DataFrame

# Convert Date/Time column datatype from object to timestamp so that we can access the month directly

In [43]:
weather_df['Date/Time']=pd.to_datetime(weather_df['Date/Time'])

In [44]:
weather_df['Date/Time']

0      2012-01-01 00:00:00
1      2012-01-01 01:00:00
2      2012-01-01 02:00:00
3      2012-01-01 03:00:00
4      2012-01-01 04:00:00
               ...        
8779   2012-12-31 19:00:00
8780   2012-12-31 20:00:00
8781   2012-12-31 21:00:00
8782   2012-12-31 22:00:00
8783   2012-12-31 23:00:00
Name: Date/Time, Length: 8784, dtype: datetime64[ns]

In [46]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   Date/Time           8784 non-null   datetime64[ns]
 1   Temp (C)            8784 non-null   float64       
 2   Dew Point Temp (C)  8784 non-null   float64       
 3   Rel Hum (%)         8784 non-null   int64         
 4   Wind Spd (km/h)     8784 non-null   int64         
 5   Visibility (km)     8784 non-null   float64       
 6   Stn Press (kPa)     8784 non-null   float64       
 7   Weather             8784 non-null   object        
dtypes: datetime64[ns](1), float64(4), int64(2), object(1)
memory usage: 549.1+ KB


In [47]:
weather_df.index

RangeIndex(start=0, stop=8784, step=1)

In [52]:
weather_df['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 

In [55]:
len(weather_df['Wind Spd (km/h)'].unique())

34

In [56]:
weather_df['Wind Spd (km/h)'].nunique()

34

In [58]:
weather_df['Weather'].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                        

In [62]:
# Number of time when the weather was exactly clear
weather_df['Weather']

0                        Fog
1                        Fog
2       Freezing Drizzle,Fog
3       Freezing Drizzle,Fog
4                        Fog
                ...         
8779                    Snow
8780                    Snow
8781                    Snow
8782                    Snow
8783                    Snow
Name: Weather, Length: 8784, dtype: object

In [63]:
weather_df.head()

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0 2012-01-01 00:00:00      -1.8                -3.9           86   
1 2012-01-01 01:00:00      -1.8                -3.7           87   
2 2012-01-01 02:00:00      -1.8                -3.4           89   
3 2012-01-01 03:00:00      -1.5                -3.2           88   
4 2012-01-01 04:00:00      -1.5                -3.3           88   

   Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                4              8.0           101.24                   Fog  
1                4              8.0           101.24                   Fog  
2                7              4.0           101.26  Freezing Drizzle,Fog  
3                6              4.0           101.27  Freezing Drizzle,Fog  
4                7              4.8           101.23                   Fog

In [66]:
weather_df['Weather'].value_counts()['Clear']

8784

In [65]:
weather_df

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0    2012-01-01 00:00:00      -1.8                -3.9           86   
1    2012-01-01 01:00:00      -1.8                -3.7           87   
2    2012-01-01 02:00:00      -1.8                -3.4           89   
3    2012-01-01 03:00:00      -1.5                -3.2           88   
4    2012-01-01 04:00:00      -1.5                -3.3           88   
...                  ...       ...                 ...          ...   
8779 2012-12-31 19:00:00       0.1                -2.7           81   
8780 2012-12-31 20:00:00       0.2                -2.4           83   
8781 2012-12-31 21:00:00      -0.5                -1.5           93   
8782 2012-12-31 22:00:00      -0.2                -1.8           89   
8783 2012-12-31 23:00:00       0.0                -2.1           86   

      Wind Spd (km/h)  Visibility (km)  Stn Press (kPa) Weather  
0                   4              8.0           101.24   Clear  
1                   4              8.0           101.24   Clear  
2                   7              4.0           101.26   Clear  
3                   6              4.0           101.27   Clear  
4                   7              4.8           101.23   Clear  
...               ...              ...              ...     ...  
8779               30              9.7           100.13   Clear  
8780               24              9.7           100.03   Clear  
8781               28              4.8            99.95   Clear  
8782               28              9.7            99.91   Clear  
8783               30             11.3            99.89   Clear  

[8784 rows x 8 columns]

In [68]:
(weather_df['Weather'].value_counts()['Clear'])

8784